apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: register-app-pipeline
spec:
  selector:
    app: register-app-pipeline 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
